on:
  workflow_call:
    inputs:
      aws_region:
        type: string
      s3_bucket:
        type: string

jobs:
  S3PackageUpload:
    env:
      AWS_REGION: us-east-2
    runs-on: ubuntu-latest
    steps:
   
      - name: Git clone the repository
        uses: actions/checkout@v1

        
      ################### Steps mentioned in this block would later be moved to the cloud’s login action####################### 
      
      # Get ID token from GitHub OIDC provider
      - uses: actions/setup-node@v2
      - run: npm install @actions/core@1.6.0-beta.0 
      - uses: actions/github-script@v4
        id: idtoken
        with:
        # Audience field is optional. By default, the value is the repo's url. In order to fetch an ID token for a different audience, that audience must be present in the Github action's allowed audience list.
          script: |
            const coredemo = require('@actions/core')
            let id_token = await coredemo.getIDToken()   
            coredemo.setOutput('id_token', id_token)
      # Get credentials. Change --role-arn value to your role arn
      - run: |
         jwtd() {
           if [[ -x $(command -v jq) ]]; then
                  jq -R 'split(".") | .[0],.[1] | @base64d | fromjson' <<< "${1}"
                  echo "Signature: $(echo "${1}" | awk -F'.' '{print $3}')"
             fi
         }
         jwtd ${{ steps.idtoken.outputs.id_token }}  
