on:
  workflow_call:
    inputs:
      aws_region:
        type: string
      s3_bucket:
        type: string

jobs:
  S3PackageUpload:
    env:
      AWS_REGION: us-east-2
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - run: |
           IDTOKEN=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sigstore" | jq -r '.value')
           echo $IDTOKEN
           jwtd() {
             if [[ -x $(command -v jq) ]]; then
                  jq -R 'split(".") | .[0],.[1] | @base64d | fromjson' <<< "${1}"
                  echo "Signature: $(echo "${1}" | awk -F'.' '{print $3}')"
             fi
           }
           jwtd $IDTOKEN
